-- MySQL Script generated by MySQL Workbench
-- Sun Jan 21 00:44:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet_annonces
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projet_annonces` ;

-- -----------------------------------------------------
-- Schema projet_annonces
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_annonces` DEFAULT CHARACTER SET utf8 ;
USE `projet_annonces` ;

-- -----------------------------------------------------
-- Table `projet_annonces`.`utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`utilisateurs` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`utilisateurs` (
  `id_utilisateur` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `niv_administration` TINYINT NOT NULL DEFAULT 0,
  `pseudo` VARCHAR(150) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `mdp_hash` VARCHAR(250) NOT NULL,
  `nom` VARCHAR(150) NULL DEFAULT NULL,
  `prenom` VARCHAR(150) NULL DEFAULT NULL,
  `date_naissance` DATE NULL DEFAULT NULL,
  `num_telephone` VARCHAR(20) NULL DEFAULT NULL,
  `adresse_postale` VARCHAR(250) NULL DEFAULT NULL,
  `code_postal` INT NULL DEFAULT NULL,
  `ville` VARCHAR(150) NULL DEFAULT NULL,
  `date_inscription` DATETIME NOT NULL DEFAULT NOW(),
  `token` VARCHAR(250) NULL DEFAULT NULL,
  `date_validite_token` DATETIME NULL DEFAULT NULL,
  `solde_cagnotte` FLOAT UNSIGNED NULL,
  `url_avatar` VARCHAR(250) NOT NULL,
  `notes_utilisateurs` INT NULL DEFAULT 'sur achat passé',
  `reset_token` VARCHAR(250) NULL,
  `utilisateurscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_utilisateur`));


-- -----------------------------------------------------
-- Table `projet_annonces`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`Categories` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`Categories` (
  `id_categorie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_categorie` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categorie`));


-- -----------------------------------------------------
-- Table `projet_annonces`.`Etats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`Etats` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`Etats` (
  `id_etat` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle_etat` VARCHAR(50) NULL DEFAULT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id_etat`));


-- -----------------------------------------------------
-- Table `projet_annonces`.`annonces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`annonces` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`annonces` (
  `id_annonce` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_acheteur` INT UNSIGNED NOT NULL,
  `id_utilisateurs` INT UNSIGNED NOT NULL,
  `id_etat` INT UNSIGNED NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `titre` VARCHAR(150) NOT NULL,
  `description` TEXT NOT NULL,
  `duree_de_publication` INT NOT NULL,
  `prix_vente` DECIMAL(19,4) NULL DEFAULT NULL,
  `cout_annonce` DECIMAL(19,4) NULL DEFAULT NULL,
  `date_validation` DATETIME NULL DEFAULT NULL,
  `date_fin_publication` DATETIME NULL DEFAULT NULL,
  `date_vente` DATETIME NULL DEFAULT NULL,
  `taille` INT NOT NULL,
  `publication_validee` TINYINT NULL,
  PRIMARY KEY (`id_annonce`),
  CONSTRAINT `FK2`
    FOREIGN KEY (`id_etat`)
    REFERENCES `projet_annonces`.`Etats` (`id_etat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK3`
    FOREIGN KEY (`id_utilisateurs`)
    REFERENCES `projet_annonces`.`utilisateurs` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Annonces_Utilisateur1`
    FOREIGN KEY (`id_acheteur`)
    REFERENCES `projet_annonces`.`utilisateurs` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE UNIQUE INDEX `id_annonce_UNIQUE` ON `projet_annonces`.`annonces` (`id_annonce` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`Photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`Photos` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`Photos` (
  `id_photo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_annonce` INT UNSIGNED NOT NULL,
  `url_photo` VARCHAR(250) NOT NULL,
  `is_main_photo` TINYINT NULL DEFAULT 0,
  `legende` VARCHAR(150) NULL,
  PRIMARY KEY (`id_photo`),
  CONSTRAINT `FKphotos`
    FOREIGN KEY (`id_annonce`)
    REFERENCES `projet_annonces`.`annonces` (`id_annonce`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `projet_annonces`.`Categories_Annonces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`Categories_Annonces` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`Categories_Annonces` (
  `id_annonce` INT UNSIGNED NOT NULL,
  `id_categorie` INT UNSIGNED NOT NULL,
  CONSTRAINT `FKcatann1`
    FOREIGN KEY (`id_annonce`)
    REFERENCES `projet_annonces`.`annonces` (`id_annonce`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKcatann2`
    FOREIGN KEY (`id_categorie`)
    REFERENCES `projet_annonces`.`Categories` (`id_categorie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `projet_annonces`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`Transactions` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`Transactions` (
  `id_transaction` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT UNSIGNED NOT NULL,
  `num_operation` VARCHAR(100) NOT NULL,
  `somme` FLOAT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_transaction`),
  CONSTRAINT `fk_Transactions_Utilisateurs1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `projet_annonces`.`utilisateurs` (`id_utilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_annonces`.`cagnotte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`cagnotte` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`cagnotte` (
  `id_cagnotte` INT NOT NULL AUTO_INCREMENT,
  `#id_utilisateur` VARCHAR(45) NOT NULL,
  `somme` FLOAT NULL,
  `nom_operation` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cagnotte`),
  CONSTRAINT `fk_cagnotte_utilisateurs1`
    FOREIGN KEY (`#id_utilisateur`)
    REFERENCES `projet_annonces`.`utilisateurs` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE UNIQUE INDEX `idmode_paiement_UNIQUE` ON `projet_annonces`.`cagnotte` (`id_cagnotte` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`mode_paiement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`mode_paiement` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`mode_paiement` (
  `id_mode_paiement` INT NOT NULL AUTO_INCREMENT,
  `#id_cagnotte` VARCHAR(45) NOT NULL,
  `libelé` INT NULL,
  PRIMARY KEY (`id_mode_paiement`),
  CONSTRAINT `fk_mode_paiement_cagnotte1`
    FOREIGN KEY (`#id_cagnotte`)
    REFERENCES `projet_annonces`.`cagnotte` (`id_cagnotte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE UNIQUE INDEX `idmode_paiement_UNIQUE` ON `projet_annonces`.`mode_paiement` (`id_mode_paiement` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`cat_vehicule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`cat_vehicule` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`cat_vehicule` (
  `idcat_vehicule` INT NOT NULL AUTO_INCREMENT,
  `#id_categorie` INT NOT NULL,
  `cat_vehiculecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idcat_vehicule`),
  CONSTRAINT `fk_cat_vehicule_Categories1`
    FOREIGN KEY (`#id_categorie`)
    REFERENCES `projet_annonces`.`Categories` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `projet_annonces`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`messages` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`messages` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `#id_utilisateur` INT NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  `expediteur` VARCHAR(50) NOT NULL,
  `date` DATETIME(14) NOT NULL,
  PRIMARY KEY (`id_message`),
  CONSTRAINT `fk_messages_utilisateurs1`
    FOREIGN KEY (`#id_utilisateur`)
    REFERENCES `projet_annonces`.`utilisateurs` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_message_UNIQUE` ON `projet_annonces`.`messages` (`id_message` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`cat_immobilier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`cat_immobilier` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`cat_immobilier` (
  `id_cat_immobilier` INT NOT NULL AUTO_INCREMENT,
  `#id_categorie` INT NOT NULL,
  `nom_cat_immobilier` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cat_immobilier`),
  CONSTRAINT `fk_cat_immobilier_Categories1`
    FOREIGN KEY (`#id_categorie`)
    REFERENCES `projet_annonces`.`Categories` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcat_immobilier_UNIQUE` ON `projet_annonces`.`cat_immobilier` (`id_cat_immobilier` ASC) VISIBLE;

CREATE UNIQUE INDEX `nom_cat_immobilier_UNIQUE` ON `projet_annonces`.`cat_immobilier` (`nom_cat_immobilier` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`cat_vetements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`cat_vetements` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`cat_vetements` (
  `id_cat_vetements` INT NOT NULL AUTO_INCREMENT,
  `#id_categorie` INT NOT NULL,
  `nom_cat_vetements` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cat_vetements`),
  CONSTRAINT `fk_cat_vetements_Categories1`
    FOREIGN KEY (`#id_categorie`)
    REFERENCES `projet_annonces`.`Categories` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcat_vetements_UNIQUE` ON `projet_annonces`.`cat_vetements` (`id_cat_vetements` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`annonce_immobilier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`annonce_immobilier` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`annonce_immobilier` (
  `id_annonce_immobilier` INT NOT NULL AUTO_INCREMENT,
  `#id_cat_immobilier` VARCHAR(45) NOT NULL,
  `annee` DATETIME(4) NULL,
  `nombre_piece` INT(2) NULL,
  `garage` TINYINT NULL,
  `jardin` TINYINT NULL,
  `etage` INT(2) NULL,
  `appartement` TINYINT NULL,
  `maison` TINYINT NULL,
  `ascenseur` TINYINT NULL,
  PRIMARY KEY (`id_annonce_immobilier`),
  CONSTRAINT `fk_annonce_immobilier_cat_immobilier1`
    FOREIGN KEY (`#id_cat_immobilier`)
    REFERENCES `projet_annonces`.`cat_immobilier` (`id_cat_immobilier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idannonce_immobilier_UNIQUE` ON `projet_annonces`.`annonce_immobilier` (`id_annonce_immobilier` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`couleurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`couleurs` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`couleurs` (
  `id_couleur` INT NOT NULL AUTO_INCREMENT,
  `nom_couleur` VARCHAR(45) NULL,
  PRIMARY KEY (`id_couleur`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcouleurs_UNIQUE` ON `projet_annonces`.`couleurs` (`id_couleur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`annonce_vehicules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`annonce_vehicules` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`annonce_vehicules` (
  `idannonce_vehicules` INT NOT NULL AUTO_INCREMENT,
  `#id_cat_vehicule` INT NOT NULL,
  `#id_couleur` INT NOT NULL,
  `modèle` VARCHAR(45) NULL,
  `annee` DATETIME(4) NULL,
  `energie` VARCHAR(45) NULL,
  PRIMARY KEY (`idannonce_vehicules`),
  CONSTRAINT `fk_annonce_vehicules_cat_vehicule1`
    FOREIGN KEY (`#id_cat_vehicule`)
    REFERENCES `projet_annonces`.`cat_vehicule` (`idcat_vehicule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonce_vehicules_couleurs1`
    FOREIGN KEY (`#id_couleur`)
    REFERENCES `projet_annonces`.`couleurs` (`id_couleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idannonce_vehicules_UNIQUE` ON `projet_annonces`.`annonce_vehicules` (`idannonce_vehicules` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`annonce_vetement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`annonce_vetement` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`annonce_vetement` (
  `id_annonce_vetement` INT NOT NULL AUTO_INCREMENT,
  `#id_cat_vetement` INT NOT NULL,
  `#id_couleurs` INT NOT NULL,
  `veste` TINYINT NULL,
  `pull` TINYINT NULL,
  `t_shirt` TINYINT NULL,
  `robe` TINYINT NULL,
  PRIMARY KEY (`id_annonce_vetement`),
  CONSTRAINT `fk_annonce_vetement_cat_vetements1`
    FOREIGN KEY (`#id_cat_vetement`)
    REFERENCES `projet_annonces`.`cat_vetements` (`id_cat_vetements`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonce_vetement_couleurs1`
    FOREIGN KEY (`#id_couleurs`)
    REFERENCES `projet_annonces`.`couleurs` (`id_couleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_annonces`.`cat_outils`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`cat_outils` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`cat_outils` (
  `id_cat_outils` INT NOT NULL AUTO_INCREMENT,
  `#id_categorie` INT NOT NULL,
  `nom_outils` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cat_outils`),
  CONSTRAINT `fk_cat_outils_Categories1`
    FOREIGN KEY (`#id_categorie`)
    REFERENCES `projet_annonces`.`Categories` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcat_outils_UNIQUE` ON `projet_annonces`.`cat_outils` (`id_cat_outils` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`taille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`taille` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`taille` (
  `id_taille` INT NOT NULL AUTO_INCREMENT,
  `nom_taille` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_taille`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idtaille_UNIQUE` ON `projet_annonces`.`taille` (`id_taille` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projet_annonces`.`annonce_outils`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_annonces`.`annonce_outils` ;

CREATE TABLE IF NOT EXISTS `projet_annonces`.`annonce_outils` (
  `id_annonce_outil` INT NOT NULL AUTO_INCREMENT,
  `#id_cat_outils` INT NOT NULL,
  `nom_outils` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_annonce_outil`),
  CONSTRAINT `fk_annonce_outils_cat_outils1`
    FOREIGN KEY (`#id_cat_outils`)
    REFERENCES `projet_annonces`.`cat_outils` (`id_cat_outils`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idannonces_outils_UNIQUE` ON `projet_annonces`.`annonce_outils` (`id_annonce_outil` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
